server {
    listen 80;
    root /usr/share/nginx/html;

    # Configuration to proxy all API routes to the Node.js backend
    location /signup { proxy_pass http://backend:3000; }
    location /login { proxy_pass http://backend:3000; }
    location /logout { proxy_pass http://backend:3000; }
    location /predict { proxy_pass http://backend:3000; }
    location /explain { proxy_pass http://backend:3000; }
    location /history { proxy_pass http://backend:3000; }
    location /history/clear { proxy_pass http://backend:3000; }

    # Main configuration for serving React files
    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass http://backend:3000/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
  }
}